LIG/LIG/config/routes.rb
Rails.application.routes.draw do

devise_for :users 

resources :main_pages do 
  get :show
end

resources  :users, :resumes 
root 'main_pages#default' 

end

LIG/LIG/app/models/user.rb
class User
	include Mongoid::Document


  validates_presence_of :name, :surname, :email, :password
  #attr_accessible :name, :surname, :email, :password, :password_confirmation, :remember_me #n existe plus dans rails4 
  #after_save :welcome_notification, if: :welcome?

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
	
  field :name, type:String
  field :surname, type:String
  field :password, type:String 

  field :admin, type:Boolean, default: false

	has_many :resumes
  accepts_nested_attributes_for :resumes,
    allow_destroy: true

  class << self
  def serialize_from_session(key, salt)
    record = to_adapter.get(key[0]["$oid"])
    record if record && record.authenticatable_salt == salt
  end
  end


private

	def welcome_notification
		UserMailer.welcome(self).deliver
	end


end

LIG/LIG/app/controllers/users_controller.rb
class UsersController < ApplicationController



	before_action :get_user , only:[:show, :edit, :update, :destroy]
	
	


	def get_user
		 if current_user.admin? 
		 	@user= User.find(params[:id]) 
		 else 
		 	@user= current_user  	
		 end
	end


	def index
		if current_user.admin
			@users = User.all
		else
			redirect_to '/', :alert => "You didn't have the right to access that page, you have been redirected"
		end

	end

	def show
		respond_to do |format|
			format.html #show.html.erb
			format.json { render json :@user}
			format.xml { render xml :@user}
			format.js 
		end
	end

	def edit
	end

	def update
	
		if @user.update(user_params)
			redirect_to @user, notice:'Updated'
		else
			render action: 'edit'
		end
		
	end

	def destroy
		@user.destroy
		respond_to do |format|
			format.js
		end
	end



	private
	def user_params
		params.require(:user).permit([:name,:surname,:email,:password])
	end

	
end

LIG/LIG/app/views/users/UselessNew.html.erb
<h1> New User </h1>

<%= form_for (User.new) do |f| %>

<div class ="field" >
	<%=f.label :name %> <br/>
	<%=f.text_field :name %> <br/>
	<%=f.label :surname %> <br/> 
	<%=f.text_field :surname %> <br/>
	<%=f.label :email %> <br/>
	<%=f.email_field :email %> <br/>
	<%=f.label :password %> <br/>
	<%=f.text_field :password %>
</div>
<div class="action" >
	<%= f.submit  %>
</div>

<%=link_to 'Back' , @user %>
<% end %>

LIG/LIG/app/views/users/_user.html.erb
<%= div_for user do %>
<tr>
	<td><%= user.name %> </td>
	<td><%= user.surname %> </td>
	<td><%= user.email %> </td>

	<div class="actions" >
		<td><%= link_to'Show', user %></td>
		<td><%= link_to'Edit', edit_user_path(user) %></td>
		<td><%= link_to'Destroy', user, method: :delete %></td>
	</div>
</tr>
<% end %>

LIG/LIG/app/views/users/destroy.js.erb
$('#<%= dom_id(@user) %>').fadeOut();

LIG/LIG/app/views/users/edit.html.erb
<!DOCTYPE html>
<html>

<h1> Edit User </h1>


<%=	form_for(@user) do |f| %>

 <div class="field">
    <%= f.label :name%><br />
    <%=f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :surname%><br />
    <%=f.text_field :surname %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

	
	<div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>
</div>

<div class="action" >
	<%= f.submit  %>
</div>
<% end %>
<%= link_to "Index", users_path %>

</html>

LIG/LIG/app/views/users/index.html.erb
<!DOCTYPE html>
<html>

<h1>Listing Users </h1>

<% if @users.size==0 %>
	<em> No User found </em>
<% else %>

<table>
	<tr>
		<th> Name </th>
		<th> Surname </th>
		<th> Email </th>
	</tr>
<div id="users" >
	<%= render @users %>
</div>
<%= link_to "Back", :back %>

<% end %>
</table>
</html>

LIG/LIG/app/views/users/show.html.erb
<!DOCTYPE html>
<html>

<h1> User </h1>
<% if @user == nil %>
<em> No User found </em>

<% else %>
<table>
<tr>
<th> Name </th>
<th> Surname </th>
<th> Email </th>
</tr>

<tr>
<td><%= @user.name %> </td>
<td><%= @user.surname %> </td>
<td><%= @user.email %> </td>


<td><%= link_to'Edit', edit_user_path(@user) %></td>
<td><%= link_to'Destroy', @user, method: :delete %></td>
</tr>

<tr>
<%= link_to "Back", :back %>
</tr>

</table>
<% end %>

</html>