LIG/LIG/config/routes.rb
Rails.application.routes.draw do

devise_for :users 

resources :main_pages do 
  get :show
end

resources  :users, :resumes 
root 'main_pages#default' 

end

LIG/LIG/app/models/skill.rb
class Skill
	include Mongoid::Document

	validates_presence_of  :skill_order, :description, :score
	validates_numericality_of :score
	validates_inclusion_of :score, in: 0..10
	


	field :skill_order, type: Integer
	field :description, type: String
	field :score, type: Integer

	embedded_in :resume

end

LIG/LIG/app/controllers/skills_controller.rb
class SkillsController < ApplicationController

	# before_action :check_auth, only:[:edit, :update, :destroy]
	before_action :get_resume_skill, only:[:show, :edit, :update , :destroy]


	def get_resume_skill
		@resume= Resume.find(params[:_id])  # a modifier par la suite  ?
		@skill=@resume.skills.find(params[:skill_id])
	end

	# def check_auth
	# 	if session[:user_id] != @resume.id
	# 		flash[:notice] ="Sorry you can't edit this resume"
	# 		redirect_to #(path a ajouter !)
	# 	end
	# end


	# def index
	# 	@skills=Resume.find(params[:_id]).skills
	# end

	def show
	
		respond_to do |format|
			format.html #show.html.erb
			format.json { render json :@skill}
			format.xml { render xml :@skill}
		end
	end

	def new
		@skill=@resume.skills.new
	end

	def edit
	end

	def create
		@skill=@resume.skills.new(skill_params)
		respond_to do |format|
			if @skill.save
				format.html { redirect_to @resume, notice: 'Skill Created'}

			else
				format.html { render action: "new" }
			end
		end
	end

	def update
	end

	def destroy
		@skill.destroy  # valable pour un sous doc ?
	end

	private
	def skill_params
		params.require(:skill).permit([:skill_order, :description, :score]) 
	end




end

LIG/LIG/app/views/skills/_index.html.erb
<h1> Listing skills </h1>

<% if @resume.skills.size==0 %>
<em> No Skill found </em>
<% else %>

<table>
<tr>
<th> Description </th>
<th> Score </th>
</tr>


<div>
<%=render @skills %>
</div>

<% end %>
</table>

LIG/LIG/app/views/skills/_new.html.erb
<h2>New Skill</h2>  
  
<%= form_for [@resume, Skill.new] do |f| %>  
  <p><%= f.label :description %> <%= f.text_field :description %></p>  
  <p><%= f.label :score %>
  <%= f.radio_button("skill", :score, 1) %></p>  
  <%= f.radio_button("skill", :score, 2) %></p>
  <%= f.radio_button("skill", :score, 3) %></p>
  <%= f.radio_button("skill", :score, 4) %></p>
  <%= f.radio_button("skill", :score, 5) %></p>
  <p><%= f.submit %></p>  
<% end %>  

LIG/LIG/app/views/skills/_show.html.erb
<tr>
<td><p>Name  <%= skill.description %> </p></td>
<td><p> <%= skill.score %> </p></td>
 
<td><%= link_to'Edit', edit_resume_path(resume) %></td>
<td><%= link_to'Destroy', resume, method: :delete %></td>
</tr>